apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apiconnect-application-set
spec:
  generators:
    - git:
        repoURL: https://github.com/stella07/guestbook.git
        revision: main
        files:
          - path: deployments/aws-build/**/config.yaml
  template:
    metadata:
      # Application name will come from the config file (e.g., "apic-d-u01")
      name: '{{name}}'
      labels:
        cloud: aws
        environment: '{{environment}}'
        region: '{{region}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/stella07/guestbook.git
        targetRevision: main
        path: resources
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
