apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apic
  namespace: default
spec:
  generators:
    - git:
        repoURL: https://github.com/stella07/guestbook.git
        revision: main
        files:
          - path: deployments/aws-build/**/config.yaml
  template:
    metadata:
      name: apic-d-u01
      labels:
        cloud: aws
        environment: development
        region: us-east-1
    spec:
      project: default
      source:
        repoURL: https://github.com/stella07/guestbook.git
        targetRevision: main
        path: resources
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated: {}   # auto create/update resources
