---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apiconnect-application-set
spec:
  generators:
    - git:
        files:
          - path: deployments/aws-build/**/config.yaml
        repoURL: https://github.com/stella07/guestbook.git
        revision: main
  template:
    metadata:
      name: apic-du02-resources
      labels:
        cloud: aws
        environment: development
        region: us-east-1
    spec:
      project: default
      source:
        repoURL: https://github.com/stella07/guestbook.git
        targetRevision: main
        path: resources
      destination:
        server: https://kubernetes.default.svc
        namespace: default
