apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apiconnect-application-set
spec:
  generators:
    - git:
        repoURL: https://github.com/stella07/guestbook.git
        revision: main
        files:
          - path: deployments/aws-build/**/config.yaml