apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-{{ .Values.env }}
spec:
  generators:
    - list:
        elements:
{{- range .Values.clusters }}
          - name: {{ .name | quote }}
            server: {{ .server | quote }}
            namespace: {{ .namespace | quote }}
{{- end }}
  template:
    metadata:
      name: "{{`{{name}}`}}-{{ .Values.env }}"
    spec:
      project: default
      source:
        repoURL: {{ .Values.repoURL | quote }}
        targetRevision: {{ .Values.targetRevision | quote }}
        chart: resources/my-app
        helm:
          valueFiles:
            - deployments/{{ .Values.env }}/{{`{{name}}`}}/values.yaml
      destination:
        server: "{{`{{server}}`}}"
        namespace: "{{`{{namespace}}`}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
