apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apiconnect-application-set
spec:
  generators:
    - git:
      files: 
       - path: deployments/aws-test/apic-t-u03.yaml
      repoURL: https://github.com/stella07/guestbook.git
      revision: main
  template:
    metadata:
      labels:
        cloud: "{{ cluster.cloud}}"
        environment: "{{ cluster.environment}}"
        region: "{{ cluster.region}}"
      name: "{{ cluster.name }}-resources"
    spec:
      destination:
        name: '{{cluster.name}}'
        namespace: default
      project: default
      source:
        path: resources
        repoURL: https://github.com/stella07/guestbook.git
        targetRevision: "{{ revision }}"
      destination:
        server: "{{ cluster.server }}"
        namespace: default
